import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Button, Container, Flex, HStack, SimpleGrid, Spacer, Icon, Box, Heading } from '@chakra-ui/react'
import CardComponent from './components/CardComponent'
import Link from 'next/link'
import queryData from '@/helpers/query'
import { fetchAllPost } from '@/actions/action'
import Preloader from './components/Preloader'
import ErrorComponent from './components/ErrorComponent'
import { ArrowLeftIcon,ArrowRightIcon } from '@chakra-ui/icons'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const {isLoading, data, error, isError} = queryData(fetchAllPost);

  if(isLoading) {
    return <Preloader />
  } else if(isError) {
    return <ErrorComponent error={error} />
  } else {

  return (
    <>
      <Head>
        <title>Post App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="container.xl">
        <Flex flexDirection='column'>
        <Button mb={10} px={10} colorScheme="telegram" alignSelf="flex-end">
          <Link href="/create-form">+Create</Link>
        </Button>
      <SimpleGrid spacing={4} templateColumns='repeat(auto-fill, minmax(200px, 1fr))'>
        {
          data.data.map(val => {
            return <CardComponent data={val} />
          })
        }
      </SimpleGrid>
        <HStack spacing={10} mt={10} alignSelf="center">
          <Button ><ArrowLeftIcon /></Button>
          <Heading color="black" size="md">{data.current_page}</Heading>
          <Button ><ArrowRightIcon /></Button>
        </HStack>
      </Flex>
      </Container>
      </main>
    </>
  )
}
}